{% set name = "fastf1" %}
{% set version = "3.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastf1-{{ version }}.tar.gz
  sha256: 9c42d0b6fce52ec518c9568f7b52aabcc9b31f2e65e56eeed48ea6f2bf2677fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.4.2, <4.0.0
    - numpy >=1.21.5,<2.0.0
    - pandas >=1.3.5,<3.0.0
    - python-dateutil
    - requests >=2.28.1
    - requests-cache >=1.0.0
    - scipy >=1.7.3,<2.0.0
    - thefuzz
    - timple >=0.1.6
    - websockets >=10.3

test:
  imports:
    - fastf1
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/theOehrly/Fast-F1
  summary: Wrapper library for F1 data and telemetry API with additional data processing capabilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
