{% set name = "fastf1" %}
{% set version = "3.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastf1-{{ version }}.tar.gz
  sha256: e580c19c485c124e27166c40c60be7ce6ab451b9f8b5a98de1a35ff3b48d6f14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - cryptography
    - matplotlib-base >=3.8.0,<4.0.0
    - numpy >=1.26.0,<3.0.0
    - pandas >=2.1.1,<3.0.0
    - platformdirs
    - pydantic
    - pyjwt
    - python-dateutil
    - requests >=2.30.0
    - requests-cache >=1.0.0
    - scipy >=1.11.0,<2.0.0
    - signalrcore
    - rapidfuzz
    - timple >=0.1.6
    - websockets >=10.3

test:
  imports:
    - fastf1
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/theOehrly/Fast-F1
  summary: Wrapper library for F1 data and telemetry API with additional data processing capabilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
