{% set name = "fastf1" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastf1-{{ version }}.tar.gz
  sha256: 9b6305575753bf67abf65413f5e1609eb0ba808f345d7ad251dbbd056b79c3aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.4.2,<4.0.0
    - numpy >=1.23.1,<3.0.0
    - pandas >=1.4.1,<3.0.0
    - python-dateutil
    - requests >=2.28.1
    - requests-cache >=1.0.0
    - scipy >=1.7.3,<2.0.0
    - rapidfuzz
    - timple >=0.1.6
    - websockets >=10.3,<14

test:
  imports:
    - fastf1
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/theOehrly/Fast-F1
  summary: Wrapper library for F1 data and telemetry API with additional data processing capabilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
