{% set name = "fastf1" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastf1-{{ version }}.tar.gz
  sha256: 45b8e6bc3faa48f476d0e6c96fcf97c097029ec4efcaddf9d583cabd8cd753ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests-cache >=0.8.0
    - pandas >=1.2.4,<2.1.0
    - numpy >=1.20.3
    - scipy >=1.6.3
    - thefuzz
    - matplotlib-base >=3.4.2
    - python-dateutil
    - timple >=0.1.2
    - requests >=2.28.0
    - websockets >=8.1

test:
  imports:
    - fastf1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/theOehrly/Fast-F1
  summary: Wrapper library for F1 data and telemetry API with additional data processing capabilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
